version: '3'

services:
    web:
        image: nginx:${NGINX_IMAGE_VERSION}
        volumes:
        - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
        - "./src:/var/www/html"
        - "./docker/nginx/logs:/var/log/nginx"
        ports:
        - "${HTTP_PORT}:80"
        environment:
        - NGINX_HOST=localhost
        restart: always
        depends_on:
        - php

    php:
        build: ./docker/php/
        restart: always
        volumes:
        - "./docker/php/php.ini:/usr/local/etc/php/php.ini"
        - "./src:/var/www/html"
        depends_on:
        - mariadb
        links:
        - mariadb

    mariadb:
        image: mariadb:${MARIADB_IMAGE_VERSION}
        environment:
        - MYSQL_DATABASE=${MARIADB_DB_NAME}
        - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWD}
        - MYSQL_USER=${MARIADB_USER}
        - MYSQL_PASSWORD=${MARIADB_USER_PASSWD}
        restart: always
        ports:
        - "${MARIADB_PORT}:3306"
        volumes:
        - "./docker/mysql-data:/var/lib/mysql"